name: omechat
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_database: ^10.5.4
  flutter:
    sdk: flutter
  audioplayers: any
  firebase_storage: ^11.7.5
  flutter_offline: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: any

flutter_icons:
  android: true
  image_path: 'assets/OmeChat_Logo.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/OmeChat_Logo_Foreground.png'

flutter:
  uses-material-design: true
  assets:
    - assets/OmeChat_Logo.png
    - assets/send.mp3
    - assets/receive.mp3
    - assets/new_message.mp3
    - assets/background.png
    - assets/scribble.png
